Add files via upload

diff --git a/system/bin/Aurora b/system/bin/Aurora
--- a/system/bin/Aurora
+++ b/system/bin/Aurora
@@ -10,114 +10,44 @@ intranet6[${#intranet6[@]}]=$(ip -6 a | awk '/inet6/ {print $2}' | grep -vE "^fe
 log() {
   local level="$1" msg="$2"
 
-  (( $# < 2 )) && { echo "Usage: log [level] [message]" >&2; return 1; }
-
   case "$level" in
-    norm)
-      printf "\033[0;32m%s - Aurora: %s\033[0m\n" "$time" "$msg"
-      [[ "$log" == "true" ]] && printf "%s - Aurora: %s\n" "$time" "$msg" >> "$Services"
+    norm)  color="0;32" ;;
+    warn)  color="0;33" ;;
+    debug) color="0;31" ;;
+  esac
+
+  printf "\033[%sm%s - Aurora: %s\033[0m\n" "$color" "$time" "$msg"
+  [[ "$log" == "true" ]] && printf "%s - Aurora: %s\n" "$time" "$msg" >> "$Services"
+}
+
+start_bin() {
+  bin_path="${KPATH}/${bin_name}"
+  [ -f "$bin_path" ] || { log debug "There is no '${bin_name}' in “${KPATH}”"; return 1; }
+  ulimit -SHn 1000000
+
+  case "$bin_name" in
+    sing-box)
+      if ! sing-box check -D "${DATADIR}" -c "${KConfig}" > "${DATADIR}/Check.log" 2>&1; then
+        log debug "sing-box configuration is invalid"
+        return 1
+      fi
+      nohup busybox setuidgid "${kernel_user_group}" "$bin_path" run -D "${DATADIR}" -c "${KConfig}" > /dev/null 2>&1 &
       ;;
-    warn)
-      printf "\033[4;31m%s - Aurora: %s\033[0m\n" "$time" "$msg"
-      [[ "$log" == "true" ]] && printf "%s - Aurora: %s\n" "$time" "$msg" >> "$Services"
-      ;;
-    debug)
-      printf "\033[0;33m%s - Aurora: %s\033[0m\n" "$time" "$msg"
-      [[ "$log" == "true" ]] && printf "%s - Aurora: %s\n" "$time" "$msg" >> "$Services"
+    mihomo)
+      if ! mihomo -t -d "${DATADIR}" -f "${KConfig}" > "${DATADIR}/Check.log" 2>&1; then
+        log debug "mihomo configuration is invalid"
+        return 1
+      fi
+      nohup busybox setuidgid "${kernel_user_group}" "$bin_path" -d "${DATADIR}" -f "${KConfig}" > "${DATADIR}/Kernel.log" 2>&1 &
       ;;
     *)
-      printf "\033[0;31m%s - Aurora: %s\033[0m\n" "$time" "$msg"
+      log debug "Unsupported kernel: $bin_name"
+      return 1
       ;;
   esac
 }
 
-start_bin() {
-
-  if [ -f "${KPATH}/${bin_name}" ] ; then
-    ulimit -SHn 1000000
-    if [ "${bin_name}" = "sing-box" ] ; then
-      if sing-box check -D ${DATADIR} -c ${KConfig} > ${DATADIR}/Check.log 2>&1 ; then
-        nohup busybox setuidgid ${kernel_user_group} ${KPATH}/sing-box run -D ${DATADIR} -c ${KConfig} > /dev/null 2>&1 &
-      else
-        log warn "“${bin_name}” is not configured properly"
-        return 1
-      fi
-    elif [ "${bin_name}" = "mihomo" ] ; then
-      if mihomo -t -d ${DATADIR} -f ${KConfig} > ${DATADIR}/Check.log 2>&1 ; then
-        nohup busybox setuidgid ${kernel_user_group} ${KPATH}/mihomo -d ${DATADIR} -f ${KConfig} > ${DATADIR}/Kernel.log 2>&1 &
-      else
-        log warn "“${bin_name}” is not configured properly"
-        return 1
-      fi
-    else
-      log warn "Unsupported Kernel: “${bin_name}”"
-      return 1
-    fi
-  else
-    log warn "There is no “${bin_name}” in “${KPATH}”"
-    return 1
-  fi
-
-}
-
-start_redirect() {
-
-  ${iptables} -t nat -N AURORA_EXTERNAL
-  ${iptables} -t nat -F AURORA_EXTERNAL
-  ${iptables} -t nat -N AURORA_LOCAL
-  ${iptables} -t nat -F AURORA_LOCAL
-
-  if [ "${dns_hijack}" = "true" ] ; then
-    ${iptables} -t nat -A AURORA_EXTERNAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
-    ${iptables} -t nat -A AURORA_LOCAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
-    ${iptables} -t nat -A AURORA_EXTERNAL -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
-    ${iptables} -t nat -A AURORA_LOCAL -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
-  fi
-
-  for subnet in ${intranet[@]} ; do
-    ${iptables} -t nat -A AURORA_EXTERNAL -d ${subnet} -j RETURN
-    ${iptables} -t nat -A AURORA_LOCAL -d ${subnet} -j RETURN
-  done
-
-  ${iptables} -t nat -A AURORA_EXTERNAL -p tcp -i lo -j REDIRECT --to-ports ${redir_port}
-
-  if [ "${ap_list}" != "" ] ; then
-    for ap in ${ap_list[@]} ; do
-      ${iptables} -t nat -A AURORA_EXTERNAL -p tcp -i ${ap} -j REDIRECT --to-ports ${redir_port}
-    done
-  fi
-
-  ${iptables} -t nat -I PREROUTING -j AURORA_EXTERNAL
-
-  ${iptables} -t nat -I AURORA_LOCAL -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -j RETURN
-
-  ${iptables} -t nat -A AURORA_LOCAL -p tcp -j REDIRECT --to-ports ${redir_port}
-
-  ${iptables} -t nat -I OUTPUT -j AURORA_LOCAL
-
-  ${iptables} -A OUTPUT -d 127.0.0.1 -p tcp -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -m tcp --dport ${redir_port} -j REJECT
-
-}
-
-stop_redirect() {
-
-  ${iptables} -t nat -D PREROUTING -j AURORA_EXTERNAL
-
-  ${iptables} -t nat -D OUTPUT -j AURORA_LOCAL
-
-  ${iptables} -D OUTPUT -d 127.0.0.1 -p tcp -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -m tcp --dport ${redir_port} -j REJECT
-  ${iptables} -D OUTPUT -d 127.0.0.1 -p tcp -m owner --uid-owner 0 --gid-owner 3005 -m tcp --dport ${redir_port} -j REJECT
-
-
-  ${iptables} -t nat -F AURORA_EXTERNAL
-  ${iptables} -t nat -X AURORA_EXTERNAL
-  ${iptables} -t nat -F AURORA_LOCAL
-  ${iptables} -t nat -X AURORA_LOCAL
-
-}
-
 start_tproxy() {
-
   if [ "${iptables}" = "ip6tables -w 100" ] ; then
     ip -6 rule add fwmark ${mark_id} table ${table_id} pref ${table_id}
     ip -6 route add local default dev lo table ${table_id}
@@ -137,14 +67,26 @@ start_tproxy() {
     ${iptables} -t mangle -A AURORA_EXTERNAL -p udp --dport 53 -j TPROXY --on-port ${tproxy_port} --tproxy-mark ${mark_id}
   fi
 
+  ${iptables} -t mangle -A AURORA_EXTERNAL -p tcp -m socket --transparent -j MARK --set-xmark ${mark_id}
+  ${iptables} -t mangle -A AURORA_EXTERNAL -p udp -m socket --transparent -j MARK --set-xmark ${mark_id}
+  ${iptables} -t mangle -A AURORA_EXTERNAL -m socket -j RETURN
+
+  ${iptables} -t mangle -A AURORA_EXTERNAL -m addrtype --dst-type LOCAL -j RETURN
+
   if [ "${iptables}" = "ip6tables -w 100" ] ; then
     for subnet6 in ${intranet6[@]} ; do
       ${iptables} -t mangle -A AURORA_EXTERNAL -d ${subnet6} -j RETURN
     done
+    ${iptables} -t mangle -N LOCAL_IP_V6
+    ${iptables} -t mangle -F LOCAL_IP_V6
+    ${iptables} -t mangle -A AURORA_EXTERNAL -j LOCAL_IP_V6
   else
     for subnet in ${intranet[@]} ; do
       ${iptables} -t mangle -A AURORA_EXTERNAL -d ${subnet} -j RETURN
     done
+    ${iptables} -t mangle -N LOCAL_IP_V4
+    ${iptables} -t mangle -F LOCAL_IP_V4
+    ${iptables} -t mangle -A AURORA_EXTERNAL -j LOCAL_IP_V4
   fi
 
   ${iptables} -t mangle -A AURORA_EXTERNAL -p tcp -i lo -j TPROXY --on-port ${tproxy_port} --tproxy-mark ${mark_id}
@@ -172,14 +114,18 @@ start_tproxy() {
     ${iptables} -t mangle -A AURORA_LOCAL -p udp --dport 53 -j MARK --set-xmark ${mark_id}
   fi
 
+  ${iptables} -t mangle -A AURORA_LOCAL -m addrtype --dst-type LOCAL -j RETURN
+
   if [ "${iptables}" = "ip6tables -w 100" ] ; then
     for subnet6 in ${intranet6[@]} ; do
       ${iptables} -t mangle -A AURORA_LOCAL -d ${subnet6} -j RETURN
     done
+    ${iptables} -t mangle -A AURORA_LOCAL -j LOCAL_IP_V6
   else
     for subnet in ${intranet[@]} ; do
       ${iptables} -t mangle -A AURORA_LOCAL -d ${subnet} -j RETURN
     done
+    ${iptables} -t mangle -A AURORA_LOCAL -j LOCAL_IP_V4
   fi
 
   ${iptables} -t mangle -A AURORA_LOCAL -p tcp -j MARK --set-xmark ${mark_id}
@@ -187,53 +133,45 @@ start_tproxy() {
 
   ${iptables} -t mangle -I OUTPUT -j AURORA_LOCAL
 
-  ${iptables} -t mangle -N DIVERT
-  ${iptables} -t mangle -F DIVERT
-
-  ${iptables} -t mangle -A DIVERT -j MARK --set-xmark ${mark_id}
-  ${iptables} -t mangle -A DIVERT -j ACCEPT
-
-  ${iptables} -t mangle -I PREROUTING -p tcp -m socket -j DIVERT
-
   if [ "${iptables}" = "ip6tables -w 100" ] ; then
     ${iptables} -A OUTPUT -d ::1 -p tcp -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -m tcp --dport ${tproxy_port} -j REJECT
   else
     ${iptables} -A OUTPUT -d 127.0.0.1 -p tcp -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -m tcp --dport ${tproxy_port} -j REJECT
   fi
 
-  if [ "${dns_hijack}" = "true" ]  && [ "${iptables}" = "iptables -w 100" ] ; then
-    ${iptables} -t nat -N DNS_EXTERNAL
-    ${iptables} -t nat -F DNS_EXTERNAL
+  if [ "${dns_hijack}" = "true" ] ; then
+    if [ "${iptables}" = "iptables -w 100" ] ; then
+      ${iptables} -t nat -N DNS_EXTERNAL
+      ${iptables} -t nat -F DNS_EXTERNAL
 
-    ${iptables} -t nat -A DNS_EXTERNAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
+      ${iptables} -t nat -A DNS_EXTERNAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
 
-    ${iptables} -t nat -I PREROUTING -j DNS_EXTERNAL
+      ${iptables} -t nat -I PREROUTING -j DNS_EXTERNAL
 
-    ${iptables} -t nat -N DNS_LOCAL
-    ${iptables} -t nat -F DNS_LOCAL
+      ${iptables} -t nat -N DNS_LOCAL
+      ${iptables} -t nat -F DNS_LOCAL
 
-    ${iptables} -t nat -A DNS_LOCAL -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -j RETURN
+      ${iptables} -t nat -A DNS_LOCAL -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -j RETURN
 
-    ${iptables} -t nat -A DNS_LOCAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
+      ${iptables} -t nat -A DNS_LOCAL -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
 
-    ${iptables} -t nat -I OUTPUT -j DNS_LOCAL
+      ${iptables} -t nat -I OUTPUT -j DNS_LOCAL
+    fi
   fi
 
   iptables -w 100 -t nat -A OUTPUT -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
   iptables -w 100 -t nat -A PREROUTING -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
-
+  ip6tables -w 100 -t nat -A OUTPUT -d ${fake_ip_range_v6} -p icmp -j DNAT --to-destination ::1
+  ip6tables -w 100 -t nat -A PREROUTING -d ${fake_ip_range_v6} -p icmp -j DNAT --to-destination ::1
 }
 
 stop_tproxy() {
-
   ip -6 rule del fwmark ${mark_id} table ${table_id} pref ${table_id}
   ip -6 route flush table ${table_id}
   ip rule del fwmark ${mark_id} table ${table_id} pref ${table_id}
   ip route flush table ${table_id}
 
   ${iptables} -t mangle -D PREROUTING -j AURORA_EXTERNAL
-
-  ${iptables} -t mangle -D PREROUTING -p tcp -m socket -j DIVERT
 
   ${iptables} -t mangle -D OUTPUT -j AURORA_LOCAL
 
@@ -243,8 +181,10 @@ stop_tproxy() {
   ${iptables} -t mangle -F AURORA_LOCAL
   ${iptables} -t mangle -X AURORA_LOCAL
 
-  ${iptables} -t mangle -F DIVERT
-  ${iptables} -t mangle -X DIVERT
+  iptables -t mangle -F LOCAL_IP_V4
+  iptables -t mangle -X LOCAL_IP_V4
+  ip6tables -t mangle -F LOCAL_IP_V6
+  ip6tables -t mangle -X LOCAL_IP_V6
 
   if [ "${iptables}" = "ip6tables -w 100" ] ; then
     ${iptables} -D OUTPUT -d ::1 -p tcp -m owner --uid-owner ${kernel_user} --gid-owner ${kernel_group} -m tcp --dport ${tproxy_port} -j REJECT
@@ -267,54 +207,50 @@ stop_tproxy() {
 
   iptables -t nat -D OUTPUT -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
   iptables -t nat -D PREROUTING -d ${fake_ip_range_v4} -p icmp -j DNAT --to-destination 127.0.0.1
-
+  ip6tables -t nat -D OUTPUT -d ${fake_ip_range_v6} -p icmp -j DNAT --to-destination ::1
+  ip6tables -t nat -D PREROUTING -d ${fake_ip_range_v6} -p icmp -j DNAT --to-destination ::1
 }
 
 case "$1" in
   iptables)
-    iptables_mode="$3"
     if [ "$2" = "true" ] ; then
-      if [ "${iptables_mode}" == "Tun" ] ; then
-        log term "${iptables_mode} iPTables rules loaded"
-      elif [ "${iptables_mode}" = "Redirect" ] ; then
-        iptables="iptables -w 100" && start_redirect > /dev/null 2>&1 && log term "Redirect iPTables rules loaded" || (log warn "Redirect iPTables rule exception" ; stop_redirect > /dev/null 2>&1)
-      elif [ "${iptables_mode}" = "TProxy" ] ; then
-        iptables="iptables -w 100" && start_tproxy > /dev/null 2>&1 && log term "TProxy iPTables rules loaded" || (log warn "TProxy iPTables rule exception" ; stop_tproxy > /dev/null 2>&1)
+      if [ "${iptmode}" = "tproxy" ] ; then
+        iptables="iptables -w 100" && start_tproxy || (log debug "iPTables rule exception" ; stop_tproxy) 2>/dev/null
         if [ "${ipv6}" = "true" ] ; then
-          iptables="ip6tables -w 100" && start_tproxy > /dev/null 2>&1 || (log warn "TProxy iP6Tables rule exception" ; stop_tproxy > /dev/null 2>&1)
+          iptables="ip6tables -w 100" && start_tproxy || (log debug "iP6Tables rule exception" ; stop_tproxy) 2>/dev/null
         fi
-      else
-        log warn "“${iptables_mode}”, Usage: Tun | TProxy | Redirect"
+        log norm "iPTables rules loaded"
       fi
-    elif [ "$2" = "false" ] ; then
-      if [ "${iptables_mode}" == "Tun" ] ; then
-        log term "${iptables_mode} iPTables rules cleared"
-      elif [ "${iptables_mode}" = "Redirect" ] ; then
-        iptables="iptables -w 100" && stop_redirect > /dev/null 2>&1
-      elif [ "${iptables_mode}" = "TProxy" ] ; then
-        iptables="iptables -w 100" && stop_tproxy > /dev/null 2>&1
-        if [ "${ipv6}" = "true" ] ; then
-          iptables="ip6tables -w 100" && stop_tproxy > /dev/null 2>&1
-        fi
-      log term "${iptables_mode} iPTables rules cleared"
-      else
-        log warn "“${iptables_mode}”, Usage: Tun | TProxy | Redirect"
+    else
+      iptables="iptables -w 100" && stop_tproxy 2>/dev/null
+      if [ "${ipv6}" = "true" ] ; then
+        iptables="ip6tables -w 100" && stop_tproxy 2>/dev/null
       fi
+      log norm "iPTables rules cleared"
     fi
     ;;
   bin)
     if [ "$2" = "true" ] ; then
-      { Aurora ipv6 ${ipv6} ; rm ${DATADIR}/Kernel.log ;} > /dev/null 2>&1
-      if start_bin && sleep 2 && pid=$(pidof ${bin_name}) ; then
-        Aurora iptables true ${iptables_mode} ; rm ${DATADIR}/Check.log
-        log norm "Core “${bin_name}” is Running, iPTables Mode: ${iptables_mode}"
+      rm -f ${DATADIR}/Kernel.log
+      Aurora ipv6 ${ipv6}
+      if [ "$bin_pid" = "" ] ; then
+        if start_bin ; then
+          Aurora iptables true
+		  rm -f ${DATADIR}/Check.log
+          log norm "Core '${bin_name}' is active"
+        else
+          log debug "Core '${bin_name}' failed to start"
+          return 1
+        fi
       else
-        log warn "Core “${bin_name}” no Started"
-        exit 1
+        log debug "Core '${bin_name}' is already running"
+        return 1
       fi
     elif [ "$2" = "false" ] ; then
-      Aurora iptables false ${iptables_mode} && { killall -15 ${bin_name} ; Aurora ipv6 true ;} > /dev/null 2>&1
-      log debug "Core “${bin_name}” has Suspend"
+      Aurora iptables false
+      killall -15 ${bin_name}
+      Aurora ipv6 true > /dev/null 2>&1
+      log norm "Core '${bin_name}' has been stopped"
     fi
     ;;
   ipv6)
@@ -332,42 +268,44 @@ case "$1" in
         echo 0 > /proc/sys/net/ipv6/conf/default/disable_ipv6
         echo 0 > /proc/sys/net/ipv6/conf/wlan0/disable_ipv6
       else
-        log warn "Unknown: $2, Usage: true | false"
+        log debug "iPv6Unknown: $2, Usage: true | false"
+	    return 1
       fi
-      log debug "iPV6Network: $2"
+      log warn "iPV6Network: $2"
     fi
     ;;
   info)
-    TEXT_API=$(curl -s -A "Mozilla/5.0" "https://v1.hitokoto.cn/?encode=text" 2>/dev/null || echo "Copyright © 2025 Tkocean")
     cpuvmrss=$(cat /proc/${bin_pid}/status 2> /dev/null | grep -w VmRSS | awk '{print $2$3}')
+    iptcheck=$(command -v "ip6tables" >/dev/null 2>&1 && echo "available" || echo "not found")
     runtime=$(busybox ps -o comm,etime | grep ${bin_name} | awk '{print $2}')
     printf '\033[0;33m%s\033[0m\n' \
-        "$time" \
-        "Mount: $SPATH" \
-        "ARCH: $ARCH" \
-        "Kernel Name: $bin_name" \
-        "Kernel UserGroup: $kernel_user:$kernel_group" \
-        "Kernel Pid: $bin_pid" \
-        "Kernel CpuVmrss: $cpuvmrss" \
-        "Kernel Runtime: $runtime" \
-        "Intranet: ${intranet[*]}" \
-        "Intranet6: ${intranet6[*]}" \
-        "Variate: $PATH" \
-        "$TEXT_API"
+      "$time" \
+      "Mount: $SPATH" \
+      "ARCH: $ARCH" \
+      "iP6Tables: $iptcheck" \
+      "Kernel Name: $bin_name" \
+      "Kernel Mode: ${iptmode}" \
+      "Kernel UserGroup: $kernel_user:$kernel_group" \
+      "Kernel Pid: $bin_pid" \
+      "Kernel CpuVmrss: $cpuvmrss" \
+      "Kernel Runtime: $runtime" \
+      "Intranet: ${intranet[*]}" \
+      "Intranet6: ${intranet6[*]}" \
+      "Variate: $PATH"
     ;;
   start)
     printf "%s - Aurora: ARCH: '%s'；Mount Path: '%s'；Datadir: '%s'\n" \
         "$time" "$ARCH" "$SPATH" "$DATADIR" > "$Services"
+    nohup inotifyd ${Config}/Net.inotify ${net_dir} > /dev/null 2>&1 &
     ;;
   *)
     CMD_LIST="
     Valid commands:
-      iptables
       info
       ipv6
       bin
     "
-    log error "ERROR: Invalid command '${1:-}'${CMD_LIST}"
-    exit 1
+    log debug "ERROR: Invalid command '${1:-}'${CMD_LIST}"
+    return 1
     ;;
 esac
